### ISSUE TITLE
Cannot run example

### ISSUE THREAD

**Issue by kokujin** [clusterinc/skit#13]
I could not follow the steps in the getting started section

```
$ ./node_modules/.bin/skit run helloworld --debug

util.js:556
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:556:43)
    at Object.<anonymous> (/Users/kokujin/Development/Research/skit_test/node_modules/skit/node_modules/http-proxy/lib/http-proxy/index.js:111:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kokujin/Development/Research/skit_test/node_modules/skit/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:456:26)
```

I am on a macpro, OSX. Thanks

**Comment by taylorhughes** [comment]
Can you run the complete helloworld project that comes with skit?

```
./node_modules/.bin/skit run ./node_modules/skit/example/helloworld
```
