### ISSUE TITLE
Cannot run examples or create new projects

### ISSUE THREAD

**Issue by kokujin** [clusterinc/skit#14]
I had posted something similar a day or two back, it was closed without the situation being resolved

Running these commands always ends with errors

```
 ./node_modules/.bin/skit run ./node_modules/skit/example/helloworld
$ ./node_modules/.bin/skit run helloworld --debug
```

```
util.js:556
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:556:43)
    at Object.<anonymous> (/Users/kokujin/Development/Research/skit_test/node_modules/skit/node_modules/http-proxy/lib/http-proxy/index.js:111:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kokujin/Development/Research/skit_test/node_modules/skit/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:456:26)
```

**Comment by taylorhughes** [comment]
This traceback is not in skit. It looks like your dependencies are not installed properly. This seems to be failing in the http-proxy npm module when including eventemitter3. What is your node version and npm version?

**Comment by dzito** [comment]
Was excited to fire up the tutorial app, but getting the same error. Here's what I have:

```
$ npm --version
2.1.8
$ node --version
v0.10.33
```

Then tried upgrading node to `v0.12.2`, re-installed skit+deps, and got same stack trace.

**Comment by kokujin** [comment]
on my system:

─$ npm --version
1.4.28

─$ node --version
v0.10.37

**Comment by danauclair** [comment]
I hit this as well, similar problems here:
https://github.com/hipache/hipache/issues/223
https://github.com/jupyter/jupyterhub/issues/237

I think this is due to a change in the version of eventemitter3 that http-proxy depends on, possibly because of this: https://github.com/nodejitsu/node-http-proxy/commit/607f96c00cbda2a6b881b8ff1db05437dbf4ce77#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Updating Skit's http-proxy version to 1.11 and running npm install seems to fix.
